### ISSUE TITLE
./configure --host avr && make works, and make doesn't use avr-g++

### ISSUE THREAD

**Issue by orion40** [edrosten/autoconf_tutorial#1]
When I enter ./configure --host avr && make, I get no error.
I installed gcc-avr using apt-get, and entering the same line gave me an error, but not the one I'm supposed to get: 
```
checking for avr-g++... avr-g++
checking whether the C++ compiler works... no
configure: error: in `/home/user/autoconf_tutorial/ex_02':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
```
However installing all of those package fixed the problem, and I now get the follow error. Here are the packages:
sudo apt-get install gcc-avr binutils-avr **avr-libc**

I'm leaving this here, in case somebody get stuck at the same place.

**Comment by edrosten** [comment]
I've added that note to the README now.
